---
- hosts: all
  tasks:
    - set_fact:
        dist: "{{ ansible_distribution | lower }}"
        major_ver: "{{ ansible_distribution_version.split('.'[0] }}"
        arch: " {{ ansible_architecture }}"
      changed_when: false
    - set_fact:
        dist_ver: "{{ dist }}_{{ major_ver }}"
        dist_ver_arch: "{{ dist }}_{{ major_ver}}_{{ arch }}"
      changed_when: false
    # Create groups by OS
    - group_by:
        key: "os_{{ dist }}"
      changed_when: false
    - group_by:
        key: "os_{{ dist_ver }}"
      changed_when: false
    - group_by:
        key: "os_{{ dist_ver_arch }}"
      changed_when: false
  tags:
    - defaults

